### ISSUE TITLE
Default Printer

### ISSUE THREAD

**Issue by jchirag0221** [faisalthaheem/automatic-printer-switcher#1]
Thanks for this amazing program.
Just wondering if you can make a minor change where you switch back to default printer after the app is opened with it's selected printer.

ie. In app if I change Chrome to Cute PDF then use the default printer for every other app where there is no printer setup.
Currently it switches the printer to Cute PDF when I open chrome but when I open lets say powerpoint for which there is no default printer setup in your app then it keeps Cute PDF as it's printer because thats what it shows in Printer setup as default printer.

It would be wonderful to switch back to the original default printer after the app is opened (with it's desired printer). so that all other app where there is no custom printer selected should go to original default printer.

**Comment by faisalthaheem** [comment]
have you tried using "Change Default Printer" option? And to assign "Cute PDF" to chrome by right clicking on chrome and selecting "edit mapping"..? this way when you have chrome in focus Cute PDF will be selected while for all other apps the printer you specified as default will be used.

**Comment by jchirag0221** [comment]
Thanks. It worked.
Actually I didn't saw that option before. But it works 100%.

Thanks once again.
